"""Move the medication safety data out of Python into a governed table.

The drug database was a dict literal in `services/drug_calculator.py`: 17
entries, no provenance on any of them, and one module-level constant declaring
the whole set UNVERIFIED. That shape has two costs. A pharmacist cannot sign
off one drug and leave another pending — approval is all or nothing. And adding
a drug means editing Python and shipping a release, so coverage can never reach
a real hospital formulary.

Here the data becomes rows. Each row carries where its numbers came from
(`source_*`) and who accepted them (`review_*`), so sign-off is per drug and is
evidence rather than a claim. Rows arrive by import from the hospital
formulary; nothing in this migration authors a clinical value.

The seed below is the existing 17 entries, transcribed mechanically from the
literal they are replacing, and every one of them lands as `pending`. Migrating
must not silently confer an approval nobody gave.

Three CHECK constraints make the module's SAFETY CONTRACT docstring enforceable
instead of advisory:

  * a drug not dosed in mg cannot be auto-calculated (heparin, insulin)
  * an absolute overdose threshold below the daily maximum is rejected — that
    is the shape of the enoxaparin defect, where a per-kg value sat in the
    absolute field and read a normal 70 mg dose as a 35x overdose
  * a pediatric bound cannot exist without its pair

Revision ID: 0003_drug_formulary
Revises: 0002_audit_integrity
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0003_drug_formulary"
down_revision: Union[str, None] = "0002_audit_integrity"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DDL = """
CREATE TABLE IF NOT EXISTS bnp_drug_formulary (
    drug_id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- ── Identity ────────────────────────────────────────────────────────────
    generic_name                TEXT NOT NULL,
    name_ar                     TEXT,
    aliases                     JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- ── Clinical ────────────────────────────────────────────────────────────
    unit                        TEXT NOT NULL,
    auto_calculate              BOOLEAN NOT NULL DEFAULT TRUE,
    dose_per_kg                 NUMERIC,
    adult_flat_min              NUMERIC,
    adult_flat_max              NUMERIC,
    adult_max_dose              NUMERIC,
    adult_max_daily             NUMERIC,
    adult_max_daily_elderly     NUMERIC,
    pediatric_min_per_kg        NUMERIC,
    pediatric_max_per_kg        NUMERIC,
    pediatric_max_daily_per_kg  NUMERIC,
    pediatric_max_doses_per_day INTEGER,
    overdose_threshold_absolute NUMERIC,
    overdose_threshold_per_kg   NUMERIC,
    frequency                   TEXT,
    route                       TEXT,
    antidote                    TEXT,
    reference_regimen           TEXT,
    contraindications           JSONB NOT NULL DEFAULT '[]'::jsonb,
    interactions                JSONB NOT NULL DEFAULT '[]'::jsonb,
    warnings                    JSONB NOT NULL DEFAULT '[]'::jsonb,
    high_risk                   BOOLEAN NOT NULL DEFAULT FALSE,

    -- ── Provenance: where the numbers came from ─────────────────────────────
    source_name                 TEXT NOT NULL,
    source_edition              TEXT,
    source_ref                  TEXT,
    imported_from_file          TEXT,
    imported_file_sha256        TEXT,
    imported_at                 TIMESTAMP,
    imported_by                 TEXT,

    -- ── Governance: who accepted them ───────────────────────────────────────
    review_status               TEXT NOT NULL DEFAULT 'pending',
    reviewed_by                 TEXT,
    reviewer_license            TEXT,
    reviewed_at                 TIMESTAMP,
    review_note                 TEXT,
    version                     INTEGER NOT NULL DEFAULT 1,

    retired_at                  TIMESTAMP,
    created_at                  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_formulary_review_status
        CHECK (review_status IN ('pending', 'approved', 'rejected')),

    CONSTRAINT ck_formulary_source_present
        CHECK (length(trim(source_name)) > 0),

    -- Drugs dosed in international units must not have a number computed for
    -- them. Heparin was previously modelled in milligrams.
    CONSTRAINT ck_formulary_unit_autocalc
        CHECK (unit = 'mg' OR auto_calculate = FALSE),

    -- A per-kg value parked in the absolute field is the enoxaparin defect.
    CONSTRAINT ck_formulary_overdose_absolute_sane
        CHECK (overdose_threshold_absolute IS NULL
               OR adult_max_daily IS NULL
               OR overdose_threshold_absolute >= adult_max_daily),

    CONSTRAINT ck_formulary_pediatric_pair
        CHECK ((pediatric_min_per_kg IS NULL) = (pediatric_max_per_kg IS NULL)),

    CONSTRAINT ck_formulary_adult_flat_pair
        CHECK ((adult_flat_min IS NULL) = (adult_flat_max IS NULL))
);

-- Retirement, not deletion — consistent with documents and chunks. A retired
-- row keeps its name, so a past audit entry naming the drug stays resolvable.
CREATE UNIQUE INDEX IF NOT EXISTS idx_formulary_generic_live
    ON bnp_drug_formulary(generic_name) WHERE retired_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_formulary_review_status
    ON bnp_drug_formulary(review_status) WHERE retired_at IS NULL;

-- Every import and every review decision is an audit event, so the log needs
-- to be able to name the drug it concerned.
ALTER TABLE bnp_audit_log ADD COLUMN IF NOT EXISTS formulary_drug_id UUID;
"""


SEED = """
INSERT INTO bnp_drug_formulary (
    generic_name,
    name_ar,
    aliases,
    unit,
    auto_calculate,
    dose_per_kg,
    adult_flat_min,
    adult_flat_max,
    adult_max_dose,
    adult_max_daily,
    adult_max_daily_elderly,
    pediatric_min_per_kg,
    pediatric_max_per_kg,
    pediatric_max_daily_per_kg,
    pediatric_max_doses_per_day,
    overdose_threshold_absolute,
    overdose_threshold_per_kg,
    frequency,
    route,
    antidote,
    reference_regimen,
    contraindications,
    interactions,
    warnings,
    high_risk,
    source_name,
    review_status
) VALUES
    ('paracetamol',
     'باراسيتامول',
     '["acetaminophen", "tylenol", "calpol"]'::jsonb,
     'mg',
     TRUE,
     15,
     500,
     1000,
     NULL,
     4000,
     3000,
     10,
     15,
     NULL,
     5,
     7500,
     NULL,
     'q6h',
     NULL,
     'N-Acetylcysteine (NAC) — initiate immediately if >150 mg/kg or per Rumack-Matthew nomogram',
     NULL,
     '["severe liver disease", "hepatic impairment", "alcohol use disorder"]'::jsonb,
     '["warfarin", "isoniazid", "rifampicin", "carbamazepine"]'::jsonb,
     '["Hepatotoxicity risk with doses above therapeutic range.", "Reduce maximum dose to 3 g/day in hepatic impairment or chronic alcohol use.", "Monitor LFTs in prolonged therapy."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('heparin',
     'هيبارين',
     '["unfractionated heparin", "ufh", "hep"]'::jsonb,
     'unit',
     FALSE,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'q8-12h (prophylaxis) or continuous infusion',
     NULL,
     'Protamine sulfate 1 mg per 100 units heparin (max 50 mg IV slowly)',
     'Prophylaxis: 5000 units SC q8–12h. Therapeutic: weight-based IV bolus and infusion per institutional protocol, titrated to aPTT. Confirm against the physician order.',
     '["active bleeding", "severe thrombocytopenia", "heparin-induced thrombocytopenia", "intracranial hemorrhage"]'::jsonb,
     '["warfarin", "aspirin", "clopidogrel", "NSAIDs", "thrombolytics"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — requires double-check by two licensed nurses.", "Monitor aPTT every 6h during infusion.", "Watch for heparin-induced thrombocytopenia (HIT) — check platelets every 2–3 days.", "Antidote: Protamine sulfate — have available at bedside."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('morphine',
     'مورفين',
     '["morphine sulfate", "ms contin"]'::jsonb,
     'mg',
     TRUE,
     0.1,
     2,
     4,
     NULL,
     120,
     NULL,
     0.05,
     0.1,
     NULL,
     NULL,
     200,
     NULL,
     'q3-4h',
     'IV/SC every 3–4 h (titrate to pain response)',
     'Naloxone 0.4–2 mg IV (repeat every 2–3 min as needed)',
     NULL,
     '["respiratory depression", "increased intracranial pressure", "severe asthma", "paralytic ileus"]'::jsonb,
     '["benzodiazepines", "alcohol", "MAO inhibitors", "CNS depressants", "gabapentin"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — RESPIRATORY DEPRESSION risk.", "Have naloxone available at bedside at all times.", "Contraindicated in: respiratory depression, increased ICP, severe asthma.", "Use extreme caution in renal/hepatic impairment.", "Monitor O2 saturation, RR, and level of consciousness."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('ibuprofen',
     'إيبوبروفين',
     '["advil", "nurofen", "brufen"]'::jsonb,
     'mg',
     TRUE,
     10,
     200,
     600,
     NULL,
     2400,
     NULL,
     5,
     10,
     40,
     NULL,
     3000,
     NULL,
     'q6-8h',
     NULL,
     'Supportive care; activated charcoal if ingested within 1h',
     NULL,
     '["active GI bleed", "renal failure", "pregnancy third trimester", "aspirin allergy", "severe heart failure"]'::jsonb,
     '["warfarin", "lithium", "methotrexate", "ACE inhibitors", "aspirin"]'::jsonb,
     '["Contraindicated in: active GI bleed, renal failure, pregnancy (3rd trimester).", "Increases GI bleed risk — use with PPI if prolonged therapy.", "Avoid in patients with cardiovascular disease."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('amoxicillin',
     'أموكسيسيلين',
     '["amoxil", "trimox"]'::jsonb,
     'mg',
     TRUE,
     25,
     250,
     500,
     NULL,
     3000,
     NULL,
     20,
     40,
     NULL,
     NULL,
     5000,
     NULL,
     'q8h',
     NULL,
     'Supportive — crystalluria management with hydration',
     NULL,
     '["penicillin allergy", "mononucleosis", "severe renal impairment"]'::jsonb,
     '["warfarin", "methotrexate", "allopurinol", "oral contraceptives"]'::jsonb,
     '["Check penicillin allergy before administration.", "Cross-reactivity with cephalosporins (~1–2%).", "Dose adjust in renal impairment (CrCl <30)."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('insulin',
     'إنسولين',
     '["insulin regular", "novolog", "humalog", "lantus", "glargine"]'::jsonb,
     'unit',
     FALSE,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     'per sliding scale or physician order',
     NULL,
     'Dextrose 50% (D50W) IV for severe hypoglycemia; glucagon 1 mg IM/SC if IV access unavailable',
     'Individualized — ALWAYS per physician order',
     '["hypoglycemia"]'::jsonb,
     '["beta blockers", "corticosteroids", "thiazide diuretics", "alcohol"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — ALWAYS perform double-check with second licensed nurse.", "Use U-100 syringes only — avoid concentration errors.", "Monitor blood glucose 30–60 min post-administration.", "HYPOGLYCEMIA ALERT: If glucose <70 mg/dL → 15 g fast-acting carbs or D50W IV.", "Never mix long-acting insulin without physician order."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('metformin',
     'ميتفورمين',
     '["glucophage"]'::jsonb,
     'mg',
     TRUE,
     NULL,
     500,
     1000,
     NULL,
     3000,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     5000,
     NULL,
     'q12h with food',
     NULL,
     'Haemodialysis for severe lactic acidosis',
     NULL,
     '["eGFR less than 30", "active hepatic disease", "contrast dye procedure", "metabolic acidosis", "heart failure"]'::jsonb,
     '["alcohol", "iodinated contrast", "cimetidine", "furosemide"]'::jsonb,
     '["Contraindicated in: eGFR <30, active hepatic disease, contrast dye procedures (hold 48h).", "Lactic acidosis risk — rare but fatal.", "Hold 24–48h before any iodinated contrast study."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('warfarin',
     'وارفارين',
     '["coumadin"]'::jsonb,
     'mg',
     TRUE,
     NULL,
     NULL,
     NULL,
     NULL,
     10,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     20,
     NULL,
     'once daily — individualized per INR',
     NULL,
     'Vitamin K (phytomenadione) + Fresh Frozen Plasma for major bleeding',
     NULL,
     '["active bleeding", "pregnancy", "recent neurosurgery", "severe hypertension"]'::jsonb,
     '["aspirin", "NSAIDs", "amoxicillin", "metronidazole", "fluconazole", "heparin", "statins", "alcohol"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — Narrow therapeutic index.", "Monitor INR regularly (target 2.0–3.0 for most indications).", "Numerous drug and food interactions — counsel patient on consistent vitamin K intake.", "Bleeding risk: monitor for signs of haemorrhage."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('vancomycin',
     'فانكومايسين',
     '["vancocin", "vanco"]'::jsonb,
     'mg',
     TRUE,
     15,
     500,
     1000,
     3000,
     4500,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     6000,
     NULL,
     'q6-12h (adjusted per renal function and levels)',
     NULL,
     'Supportive care; haemodialysis for severe overdose',
     NULL,
     '["vancomycin allergy", "severe hearing impairment"]'::jsonb,
     '["aminoglycosides", "furosemide", "amphotericin B", "ciclosporin", "NSAIDs"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — Nephrotoxic and ototoxic.", "Monitor renal function (SCr, BUN) at baseline and every 48–72h.", "Therapeutic drug monitoring required: target trough 10–20 mg/L (or AUC/MIC 400–600).", "Infuse over ≥60 min to avoid Red Man Syndrome (flushing, hypotension).", "Dose-adjust in renal impairment — use vancomycin nomogram.", "Audiometry monitoring if prolonged therapy."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('gentamicin',
     'جنتامايسين',
     '["garamycin"]'::jsonb,
     'mg',
     TRUE,
     1.5,
     NULL,
     NULL,
     160,
     480,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     640,
     NULL,
     'q8h (or once-daily extended-interval dosing)',
     NULL,
     'Supportive; haemodialysis for severe toxicity',
     NULL,
     '["aminoglycoside allergy", "myasthenia gravis", "severe renal failure"]'::jsonb,
     '["vancomycin", "furosemide", "amphotericin B", "ciclosporin", "neuromuscular blockers"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — Nephrotoxic and ototoxic aminoglycoside.", "Monitor serum levels: peak 5–10 mg/L, trough <2 mg/L (traditional dosing).", "Check renal function before each dose; avoid in severe renal impairment.", "Monitor for vestibular and auditory toxicity.", "Avoid concurrent nephrotoxic agents."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('furosemide',
     'فيوروسيمايد',
     '["lasix", "frusemide"]'::jsonb,
     'mg',
     TRUE,
     0.5,
     20,
     80,
     NULL,
     600,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     1000,
     NULL,
     'q6-24h (titrated to response)',
     NULL,
     'Fluid replacement; electrolyte correction',
     NULL,
     '["anuria", "sulfonamide allergy", "severe electrolyte depletion", "hepatic coma"]'::jsonb,
     '["gentamicin", "vancomycin", "digoxin", "lithium", "NSAIDs", "ACE inhibitors"]'::jsonb,
     '["Monitor electrolytes (K+, Na+, Mg2+) regularly — hypokalemia risk.", "Assess fluid status and urine output before and after administration.", "Risk of ototoxicity with high doses — avoid concurrent aminoglycosides.", "Monitor blood pressure for hypotension.", "Hold if urine output <30 mL/h — report to physician."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('digoxin',
     'ديجوكسين',
     '["lanoxin"]'::jsonb,
     'mg',
     TRUE,
     NULL,
     NULL,
     NULL,
     NULL,
     0.25,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     0.5,
     NULL,
     'once daily (individualized by levels)',
     NULL,
     'Digoxin-specific antibody fragments (DigiFab) for toxicity',
     NULL,
     '["ventricular fibrillation", "hypertrophic obstructive cardiomyopathy", "Wolff-Parkinson-White syndrome", "hypokalaemia"]'::jsonb,
     '["amiodarone", "verapamil", "diltiazem", "quinidine", "furosemide", "spironolactone"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — Narrow therapeutic index (target 0.5–2.0 ng/mL).", "Check apical pulse for 1 full minute before administration — hold if <60 bpm.", "Monitor serum digoxin levels, K+, Mg2+ regularly.", "Signs of toxicity: nausea, vomiting, visual disturbances (yellow/green halos), bradycardia.", "Dose-reduce significantly in renal impairment.", "Antidote: DigiFab — available in resuscitation trolley."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('enoxaparin',
     'إينوكسابارين',
     '["clexane", "lovenox", "lmwh"]'::jsonb,
     'mg',
     TRUE,
     1.0,
     NULL,
     NULL,
     NULL,
     180,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     2,
     'q12h (prophylaxis: once daily)',
     NULL,
     'Protamine sulfate (partial reversal — 60% of anti-Xa activity)',
     NULL,
     '["active major bleeding", "heparin-induced thrombocytopenia", "severe renal failure (CrCl <15)", "prosthetic heart valve"]'::jsonb,
     '["warfarin", "aspirin", "NSAIDs", "thrombolytics", "clopidogrel"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — Low Molecular Weight Heparin.", "Dose-adjust in renal impairment (CrCl <30 — use UFH instead).", "Anti-Xa monitoring for obese patients (BMI >40) or renal impairment.", "Do not administer IM — subcutaneous injection only.", "Monitor platelet count — risk of HIT (lower than UFH).", "Hold 12–24h before neuraxial anaesthesia."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('metoprolol',
     'ميتوبرولول',
     '["lopressor", "toprol", "betaloc"]'::jsonb,
     'mg',
     TRUE,
     NULL,
     25,
     100,
     NULL,
     400,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     1000,
     NULL,
     'q12-24h (IR: q6-12h)',
     NULL,
     'Atropine for bradycardia; glucagon 5–10 mg IV for haemodynamic instability',
     NULL,
     '["cardiogenic shock", "severe bradycardia", "sick sinus syndrome", "severe asthma", "second/third degree AV block"]'::jsonb,
     '["verapamil", "diltiazem", "digoxin", "clonidine", "insulin", "NSAIDs"]'::jsonb,
     '["Do NOT abruptly discontinue — taper dose over 1–2 weeks (risk of rebound hypertension/angina).", "Monitor heart rate and blood pressure before each dose — hold if HR <50 bpm or SBP <90 mmHg.", "Use with caution in asthma/COPD — may worsen bronchospasm.", "Masks signs of hypoglycaemia in diabetic patients."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('omeprazole',
     'أوميبرازول',
     '["losec", "prilosec"]'::jsonb,
     'mg',
     TRUE,
     NULL,
     20,
     40,
     NULL,
     120,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     360,
     NULL,
     'once daily (before meals)',
     NULL,
     'Supportive care',
     NULL,
     '["hypersensitivity to PPIs"]'::jsonb,
     '["clopidogrel", "methotrexate", "warfarin", "atazanavir", "iron salts"]'::jsonb,
     '["Take 30–60 minutes before first meal of the day for maximum efficacy.", "Long-term use (>1 year): monitor for hypomagnesaemia, B12 deficiency, bone density.", "Reduces clopidogrel effectiveness — avoid combination if possible.", "Increased risk of C. difficile infection with prolonged use."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('amiodarone',
     'أميودارون',
     '["cordarone", "pacerone"]'::jsonb,
     'mg',
     TRUE,
     NULL,
     100,
     200,
     NULL,
     400,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     800,
     NULL,
     'once daily (maintenance); loading doses per protocol',
     NULL,
     'Supportive care; ICD for VF unresponsive to therapy',
     NULL,
     '["severe sinus node dysfunction", "second/third degree AV block", "iodine allergy", "thyroid disorders", "pregnancy"]'::jsonb,
     '["warfarin", "digoxin", "statins", "ciclosporin", "quinolones", "beta blockers"]'::jsonb,
     '["🔴 HIGH RISK MEDICATION — Multiple serious toxicities.", "Monitor thyroid function (TFTs) every 6 months — both hypo and hyperthyroidism possible.", "Monitor LFTs and pulmonary function — risk of hepatotoxicity and pulmonary toxicity.", "Eye examinations required annually — corneal microdeposits and optic neuropathy.", "Photosensitivity — counsel patient to use sunscreen.", "Extremely long half-life (40–55 days) — effects persist long after discontinuation."]'::jsonb,
     TRUE,
     'seed — unverified, pending pharmacist review',
     'pending'),
    ('ceftriaxone',
     'سيفترياكسون',
     '["rocephin"]'::jsonb,
     'mg',
     TRUE,
     50,
     1000,
     2000,
     NULL,
     4000,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     8000,
     NULL,
     'once daily (q12h for severe infections)',
     NULL,
     'Supportive care',
     NULL,
     '["cephalosporin allergy", "penicillin allergy (cross-reactivity ~1–2%)", "neonates with hyperbilirubinaemia", "IV calcium co-administration in neonates"]'::jsonb,
     '["warfarin", "calcium-containing IV solutions", "aminoglycosides"]'::jsonb,
     '["Do NOT co-administer with calcium-containing IV solutions (risk of precipitation — fatal in neonates).", "Check penicillin allergy history — cross-reactivity possible.", "Reconstitute with appropriate diluent — NOT calcium-containing solutions.", "Biliary sludge possible with prolonged use."]'::jsonb,
     FALSE,
     'seed — unverified, pending pharmacist review',
     'pending')
ON CONFLICT DO NOTHING;
"""


def upgrade() -> None:
    op.execute(DDL)
    op.execute(SEED)


def downgrade() -> None:
    raise NotImplementedError(
        "Not reversible: dropping the formulary would discard the pharmacist "
        "review decisions recorded against each drug."
    )
