const colors = {
  light: {
    text: "#0F172A",
    tint: "#8B5CF6",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#E2E8F0",
    secondaryForeground: "#1E293B",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#8B5CF6",
    accentForeground: "#0F172A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#CBD5E1",
    input: "#E2E8F0",
    pharmacy: "#4CC9F0",
    policies: "#8B5CF6",
    quality: "#7C3AED",
  },

  dark: {
    text: "#F8FAFC",
    tint: "#8B5CF6",
    background: "#0A0A0F",
    foreground: "#F8FAFC",
    card: "#1A1A2E",
    cardForeground: "#F8FAFC",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#2D1B4E",
    secondaryForeground: "#F8FAFC",
    muted: "#1A1A2E",
    mutedForeground: "#94A3B8",
    accent: "#8B5CF6",
    accentForeground: "#F8FAFC",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1B4E",
    input: "#1A1A2E",
    pharmacy: "#4CC9F0",
    policies: "#8B5CF6",
    quality: "#7C3AED",
  },

  radius: 12,
};

export default colors;
